Update Botocore to 1.34.131
aio-libs/aiobotocore pull request #1122
Opened 2024-06-21 18:58 UTC by lou-k

### Description of Change
Updates botocore to 1.34.131

There is no added functionality in 1.34.131:
```
git diff --name-status 1.34.106...1.34.131 botocore/ | grep py$
M	botocore/__init__.py
M	botocore/retries/standard.py
M	botocore/utils.py
```

but I'd like to use the latest `boto3` in my project, and the existing `<1.34.107` is causing a dependency issue.

### Assumptions
*I got some errors on `make cov` before I made any changes. I'm assuming that is an issue with my local environment and CICD will pass here...*

### Checklist for All Submissions
* [x] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* ~[ ] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details):~
* ~[ ] If this is providing a new feature  (can be provided via link to issue with these details):~

### Checklist when updating botocore and/or aiohttp versions

* [x] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [x] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [x] I have ensured that the awscli/boto3 versions match the updated botocore version

### Tests Run Locally

```
pytest -sv tests/test_patches.py 
 ======================================== test session starts  ========================================
platform darwin -- Python 3.12.3, pytest-8.1.1, pluggy-1.5.0 -- /Users/lou/.local/share/virtualenvs/aiobotocore-UGsiy0fU/bin/python
cachedir: /tmp/pytest_aiobotocore_cache
rootdir: /Users/lou/repos/aiobotocore
configfile: pyproject.toml
plugins: cov-5.0.0, asyncio-0.21.2, xdist-3.5.0
asyncio: mode=Mode.AUTO
collected 2 items                                                                                                                                                                                                                                            

tests/test_patches.py::test_protocol_parsers PASSED
tests/test_patches.py::test_patches Botocore version: 1.34.131
PASSED

 ======================================== 2 passed in 0.20s ========================================

```

Thanks for the easy-to-follow guide on updating this!

2024-06-21 19:06 UTC, jakob-keller requested changes

2024-06-21 19:06 UTC, jakob-keller commented on setup.py
> -    'botocore>=1.34.70,<1.34.107',
Since there appear to be no relevant upstream changes, then lower bound can be kept at 1.34.70.

2024-06-21 19:06 UTC, jakob-keller commented on setup.py
> -    'awscli': ['awscli>=1.32.70,<1.32.107'],
Since there appear to be no relevant upstream changes, then lower bound can be kept at 1.32.70 and 1.34.70 respectively.

2024-06-21 20:18 UTC, lou-k commented
thanks for the eyes, @jakob-keller !

2024-06-21 20:21 UTC, jakob-keller approved these changes

2024-06-24 09:20 UTC, jakob-keller commented
closes #1123

2024-06-24 17:43 UTC, thehesiod commented
oh we hit this error at work, need to upgrade docker/requests IIRC

2024-06-24 18:14 UTC, thehesiod commented
ughh, ci tool

2024-06-24 18:23 UTC, merged

2024-06-24 18:25 UTC, thehesiod commented
sweet!